// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SystemStatusDependenciesAnalyticsDatasource.
const (
	SystemStatusDependenciesAnalyticsDatasourceDegraded SystemStatusDependenciesAnalyticsDatasource = "degraded"
	SystemStatusDependenciesAnalyticsDatasourceOk       SystemStatusDependenciesAnalyticsDatasource = "ok"
)

// Valid indicates whether the value is a known member of the SystemStatusDependenciesAnalyticsDatasource enum.
func (e SystemStatusDependenciesAnalyticsDatasource) Valid() bool {
	switch e {
	case SystemStatusDependenciesAnalyticsDatasourceDegraded:
		return true
	case SystemStatusDependenciesAnalyticsDatasourceOk:
		return true
	default:
		return false
	}
}

// Defines values for SystemStatusDependenciesMetadata.
const (
	SystemStatusDependenciesMetadataDown SystemStatusDependenciesMetadata = "down"
	SystemStatusDependenciesMetadataOk   SystemStatusDependenciesMetadata = "ok"
)

// Valid indicates whether the value is a known member of the SystemStatusDependenciesMetadata enum.
func (e SystemStatusDependenciesMetadata) Valid() bool {
	switch e {
	case SystemStatusDependenciesMetadataDown:
		return true
	case SystemStatusDependenciesMetadataOk:
		return true
	default:
		return false
	}
}

// Defines values for SystemStatusDependenciesRedis.
const (
	Down SystemStatusDependenciesRedis = "down"
	Ok   SystemStatusDependenciesRedis = "ok"
)

// Valid indicates whether the value is a known member of the SystemStatusDependenciesRedis enum.
func (e SystemStatusDependenciesRedis) Valid() bool {
	switch e {
	case Down:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// AssetWrite defines model for AssetWrite.
type AssetWrite struct {
	Document map[string]interface{} `json:"document"`
	Slug     string                 `json:"slug"`
	Summary  *string                `json:"summary,omitempty"`
	Title    string                 `json:"title"`
}

// QuerySpec defines model for QuerySpec.
type QuerySpec struct {
	DatasetKey string                    `json:"datasetKey"`
	Dimensions *[]string                 `json:"dimensions,omitempty"`
	Filters    *[]map[string]interface{} `json:"filters,omitempty"`
	Limit      *int                      `json:"limit,omitempty"`
	Metrics    *[]string                 `json:"metrics,omitempty"`
	Offset     *int                      `json:"offset,omitempty"`
	Sort       *[]map[string]interface{} `json:"sort,omitempty"`
	TimeRange  struct {
		End   openapi_types.Date `json:"end"`
		Start openapi_types.Date `json:"start"`
	} `json:"timeRange"`
}

// SystemStatus defines model for SystemStatus.
type SystemStatus struct {
	Capabilities []string `json:"capabilities"`
	Dependencies struct {
		AnalyticsDatasource SystemStatusDependenciesAnalyticsDatasource `json:"analyticsDatasource"`
		Metadata            SystemStatusDependenciesMetadata            `json:"metadata"`
		Redis               SystemStatusDependenciesRedis               `json:"redis"`
	} `json:"dependencies"`
	Principal string `json:"principal"`
	Service   string `json:"service"`
	Version   string `json:"version"`
}

// SystemStatusDependenciesAnalyticsDatasource defines model for SystemStatus.Dependencies.AnalyticsDatasource.
type SystemStatusDependenciesAnalyticsDatasource string

// SystemStatusDependenciesMetadata defines model for SystemStatus.Dependencies.Metadata.
type SystemStatusDependenciesMetadata string

// SystemStatusDependenciesRedis defines model for SystemStatus.Dependencies.Redis.
type SystemStatusDependenciesRedis string

// Id defines model for Id.
type Id = openapi_types.UUID

// Kind defines model for Kind.
type Kind = interface{}

// UpdateAssetParams defines parameters for UpdateAsset.
type UpdateAssetParams struct {
	IfMatch string `json:"If-Match"`
}

// RestoreRevisionParams defines parameters for RestoreRevision.
type RestoreRevisionParams struct {
	IfMatch string `json:"If-Match"`
}

// ExecuteQueryParams defines parameters for ExecuteQuery.
type ExecuteQueryParams struct {
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// CreateAssetJSONRequestBody defines body for CreateAsset for application/json ContentType.
type CreateAssetJSONRequestBody = AssetWrite

// UpdateAssetJSONRequestBody defines body for UpdateAsset for application/json ContentType.
type UpdateAssetJSONRequestBody = AssetWrite

// ExecuteQueryJSONRequestBody defines body for ExecuteQuery for application/json ContentType.
type ExecuteQueryJSONRequestBody = QuerySpec

// ValidateQueryJSONRequestBody defines body for ValidateQuery for application/json ContentType.
type ValidateQueryJSONRequestBody = QuerySpec

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /assets/{kind})
	ListAssets(w http.ResponseWriter, r *http.Request, kind Kind)

	// (POST /assets/{kind})
	CreateAsset(w http.ResponseWriter, r *http.Request, kind Kind)

	// (DELETE /assets/{kind}/{id})
	ArchiveAsset(w http.ResponseWriter, r *http.Request, kind Kind, id Id)

	// (GET /assets/{kind}/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, kind Kind, id Id)

	// (PUT /assets/{kind}/{id})
	UpdateAsset(w http.ResponseWriter, r *http.Request, kind Kind, id Id, params UpdateAssetParams)

	// (GET /assets/{kind}/{id}/revisions)
	ListRevisions(w http.ResponseWriter, r *http.Request, kind Kind, id Id)

	// (POST /assets/{kind}/{id}/revisions/{revision}/restore)
	RestoreRevision(w http.ResponseWriter, r *http.Request, kind Kind, id Id, revision int, params RestoreRevisionParams)

	// (GET /datasets)
	ListDatasets(w http.ResponseWriter, r *http.Request)

	// (GET /datasets/{key})
	GetDataset(w http.ResponseWriter, r *http.Request, key string)

	// (GET /events)
	Events(w http.ResponseWriter, r *http.Request)

	// (GET /health/live)
	Live(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	Ready(w http.ResponseWriter, r *http.Request)

	// (POST /query/execute)
	ExecuteQuery(w http.ResponseWriter, r *http.Request, params ExecuteQueryParams)

	// (POST /query/validate)
	ValidateQuery(w http.ResponseWriter, r *http.Request)

	// (GET /system/status)
	SystemStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /assets/{kind})
func (_ Unimplemented) ListAssets(w http.ResponseWriter, r *http.Request, kind Kind) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /assets/{kind})
func (_ Unimplemented) CreateAsset(w http.ResponseWriter, r *http.Request, kind Kind) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /assets/{kind}/{id})
func (_ Unimplemented) ArchiveAsset(w http.ResponseWriter, r *http.Request, kind Kind, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /assets/{kind}/{id})
func (_ Unimplemented) GetAsset(w http.ResponseWriter, r *http.Request, kind Kind, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /assets/{kind}/{id})
func (_ Unimplemented) UpdateAsset(w http.ResponseWriter, r *http.Request, kind Kind, id Id, params UpdateAssetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /assets/{kind}/{id}/revisions)
func (_ Unimplemented) ListRevisions(w http.ResponseWriter, r *http.Request, kind Kind, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /assets/{kind}/{id}/revisions/{revision}/restore)
func (_ Unimplemented) RestoreRevision(w http.ResponseWriter, r *http.Request, kind Kind, id Id, revision int, params RestoreRevisionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /datasets)
func (_ Unimplemented) ListDatasets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /datasets/{key})
func (_ Unimplemented) GetDataset(w http.ResponseWriter, r *http.Request, key string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /events)
func (_ Unimplemented) Events(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health/live)
func (_ Unimplemented) Live(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health/ready)
func (_ Unimplemented) Ready(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /query/execute)
func (_ Unimplemented) ExecuteQuery(w http.ResponseWriter, r *http.Request, params ExecuteQueryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /query/validate)
func (_ Unimplemented) ValidateQuery(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /system/status)
func (_ Unimplemented) SystemStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", chi.URLParam(r, "kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAssets(w, r, kind)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", chi.URLParam(r, "kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAsset(w, r, kind)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveAsset operation middleware
func (siw *ServerInterfaceWrapper) ArchiveAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", chi.URLParam(r, "kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveAsset(w, r, kind, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", chi.URLParam(r, "kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, kind, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAsset operation middleware
func (siw *ServerInterfaceWrapper) UpdateAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", chi.URLParam(r, "kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateAssetParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAsset(w, r, kind, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRevisions operation middleware
func (siw *ServerInterfaceWrapper) ListRevisions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", chi.URLParam(r, "kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRevisions(w, r, kind, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreRevision operation middleware
func (siw *ServerInterfaceWrapper) RestoreRevision(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", chi.URLParam(r, "kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "revision" -------------
	var revision int

	err = runtime.BindStyledParameterWithOptions("simple", "revision", chi.URLParam(r, "revision"), &revision, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "revision", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RestoreRevisionParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreRevision(w, r, kind, id, revision, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDatasets operation middleware
func (siw *ServerInterfaceWrapper) ListDatasets(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDatasets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDataset operation middleware
func (siw *ServerInterfaceWrapper) GetDataset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataset(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Events operation middleware
func (siw *ServerInterfaceWrapper) Events(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Events(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Live operation middleware
func (siw *ServerInterfaceWrapper) Live(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Live(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ready operation middleware
func (siw *ServerInterfaceWrapper) Ready(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ready(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecuteQuery operation middleware
func (siw *ServerInterfaceWrapper) ExecuteQuery(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteQueryParams

	// ------------- Optional query parameter "refresh" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "refresh", r.URL.Query(), &params.Refresh, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refresh"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecuteQuery(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateQuery operation middleware
func (siw *ServerInterfaceWrapper) ValidateQuery(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateQuery(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemStatus operation middleware
func (siw *ServerInterfaceWrapper) SystemStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{kind}", wrapper.ListAssets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets/{kind}", wrapper.CreateAsset)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/assets/{kind}/{id}", wrapper.ArchiveAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{kind}/{id}", wrapper.GetAsset)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/assets/{kind}/{id}", wrapper.UpdateAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{kind}/{id}/revisions", wrapper.ListRevisions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets/{kind}/{id}/revisions/{revision}/restore", wrapper.RestoreRevision)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/datasets", wrapper.ListDatasets)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/datasets/{key}", wrapper.GetDataset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.Events)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/live", wrapper.Live)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/ready", wrapper.Ready)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/query/execute", wrapper.ExecuteQuery)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/query/validate", wrapper.ValidateQuery)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/status", wrapper.SystemStatus)
	})

	return r
}
